theme: jekyll-theme-minimal
title: Conrad Ronk
description: Portfolio Site
show_downloads: False
navigation:
  - title: Home
    url: https://conradronk.github.io/
  - title: Transit Exploration
    url: https://conradronk.github.io/Transit-Data-Exploration/
  - title: FB Messenger Analytics
    url: https://conradronk.github.io/Messenger-Analytics/
